//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectDotNetv2
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookMeeting
    {
        public int Book_ID { get; set; }
        public string LecturerName { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Description { get; set; }
        public int data_tableLct_ID { get; set; }
    }
}
